### ISSUE TITLE
slug никак не используется. нужно какой то список новостей задать хардкодом и выводить.

### ISSUE THREAD

**Issue by paladinbbk** [kda23/symfony#2]
https://github.com/kda23/symfony/blob/053c6b3bc9606dd32e0a7735cc8d05657ff715ad/src/Controller/ArticleController.php#L21

**Comment by paladinbbk** [comment]
Наверно уже не стоит. завтра покажу как через базу данных работать

**Comment by paladinbbk** [comment]
https://twig.symfony.com/doc/2.x/tags/for.html

**Comment by kda23** [comment]
Исправил. Slug заменил на articleid, при помощи которого выводится список новостей из базы данных

**Comment by kda23** [comment]
Вернул slug, при помощи которого выводится список новостей
