### ISSUE TITLE
все не так

### ISSUE THREAD

**Issue by paladinbbk** [kda23/symfony#4]
https://github.com/kda23/symfony/blob/16937b7227f71572629efe7d35f6c72af6fc166f/src/Controller/ArticleController.php#L59

**Comment by paladinbbk** [comment]
тайпхитинга в экшене нету.
называется slug но работать будет только по id

**Comment by kda23** [comment]
Исправил https://github.com/kda23/symfony/blob/master/src/Controller/MainController.php
