### ISSUE TITLE
app.request.pathinfo тут не нужен. Слаги перепутал категории и поста!!!

### ISSUE THREAD

**Issue by paladinbbk** [kda23/symfony#5]
https://github.com/kda23/symfony/blob/341f09eaf5e47cea9115df9f959cd5bfd1be6257/templates/caterories.html.twig#L15

**Comment by kda23** [comment]
Заменил {{ app.request.pathinfo }}, в коде выглядит следующим образом
`<li><a` href="{{ path('category', {'slugCategory' : category.slug}) }}{{ path('category', {'slugCategory' : post.slug}) }}">{{ post.title `}}</a></li>`
При помощи {{ path('category', {'slugCategory' : post.slug}) }} генерируется вторая часть url - slug статьи, которая принадлежит данному разделу
https://github.com/kda23/symfony/blob/master/templates/caterories.html.twig
